//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.26 at 11:22:32 AM GMT 
//


package uk.ac.ox.it.ords.api.statistics.configuration.servers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}serverList"/>
 *       &lt;/sequence>
 *       &lt;attribute name="testEnvironment" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hostName" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serverList"
})
@XmlRootElement(name = "ordsServerConfig")
public class OrdsServerConfig {

    @XmlElement(required = true)
    protected ServerList serverList;
    @XmlAttribute(name = "testEnvironment", required = true)
    protected boolean testEnvironment;
    @XmlAttribute(name = "hostName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String hostName;

    /**
     * Gets the value of the serverList property.
     * 
     * @return
     *     possible object is
     *     {@link ServerList }
     *     
     */
    public ServerList getServerList() {
        return serverList;
    }

    /**
     * Sets the value of the serverList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerList }
     *     
     */
    public void setServerList(ServerList value) {
        this.serverList = value;
    }

    /**
     * Gets the value of the testEnvironment property.
     * 
     */
    public boolean isTestEnvironment() {
        return testEnvironment;
    }

    /**
     * Sets the value of the testEnvironment property.
     * 
     */
    public void setTestEnvironment(boolean value) {
        this.testEnvironment = value;
    }

    /**
     * Gets the value of the hostName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * Sets the value of the hostName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostName(String value) {
        this.hostName = value;
    }

}
